### ISSUE TITLE
empty retries field

### ISSUE THREAD

**Issue by daroczig** [nfultz/aws_batch#1]
Results in 

```
java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at njnm.plugins.aws_batch.AwsBatchBuilder.<init>(AwsBatchBuilder.java:78)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.kohsuke.stapler.RequestImpl.invokeConstructor(RequestImpl.java:529)
	at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:783)
	at org.kohsuke.stapler.RequestImpl.access$200(RequestImpl.java:83)
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:678)
Caused: java.lang.IllegalArgumentException: Failed to instantiate class njnm.plugins.aws_batch.AwsBatchBuilder from {"jobname":"test","jobdefinition":"test:1","jobqueue":"test","command":"[whoami]","vcpu":"1","memory":"256","retries":"","stapler-class":"njnm.plugins.aws_batch.AwsBatchBuilder","$class":"njnm.plugins.aws_batch.AwsBatchBuilder"}
```

**Comment by nfultz** [comment]
I tried to fix this but the jenkins web UI is a jerk. So for now caveat emptor.
